import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box, Heading } from "grommet";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>Agitur</Heading>
      <div className={styles.grid}>
        <Box direction="row" justify="center" align="center" gap="small">
          <img
            src="https://s2.coinmarketcap.com/static/img/coins/64x64/512.png"
            height="32"
            width="32"
            alt="XLM"
          />
          <p className={styles.description}>XLM</p>
        </Box>
      </div>
    </div>
  );
}
